/**
 * Skill Translator — converts canonical skills to each agent's native format.
 *
 * Supported agents:
 *   - hermes: SKILL.md in ~/.hermes/skills/{category}/{name}/  (already in store.ts)
 *   - claude-code: single CLAUDE.md with all skills merged
 *   - cursor: .cursorrules with skills section
 */

import { writeFileSync, existsSync, readFileSync, mkdirSync } from 'fs'
import { join } from 'path'
import type { CanonicalSkill, AgentId } from './types'
import { loadIndex, getSkill } from './store'

// ── Claude Code: CLAUDE.md ──

/**
 * Build a complete CLAUDE.md from all active skills marked for claude-code.
 * Each skill becomes a ## section with description and instructions.
 */
export function buildClaudeMd(projectDir?: string): string {
  const dir = projectDir || process.cwd()
  const idx = loadIndex()
  const activeSkills = idx.skills.filter(s => s.active && s.activeFor.includes('claude-code'))

  const sections: string[] = []
  sections.push('# DeskApp Skills')
  sections.push('')
  sections.push('> Auto-generated by DeskApp Skill Hub. DO NOT EDIT MANUALLY.')
  sections.push(`> ${activeSkills.length} skills active for Claude Code.`)
  sections.push('')

  for (const entry of activeSkills) {
    const skill = getSkill(entry.name)
    if (!skill) continue
    const adapter = skill.adapters?.claudeCode
    const title = adapter?.sectionTitle || skill.name

    sections.push(`## ${title}`)
    if (skill.description) {
      sections.push(`> ${skill.description}`)
    }
    if (skill.trigger) {
      sections.push(`Trigger: ${skill.trigger}`)
    }
    sections.push('')
    if (skill.instructions) {
      sections.push(skill.instructions)
    }
    if (adapter?.extraInstructions) {
      sections.push('')
      sections.push(adapter.extraInstructions)
    }
    sections.push('')
    sections.push('---')
    sections.push('')
  }

  return sections.join('\n')
}

export function syncToClaudeCode(projectDir?: string): { ok: boolean; path: string; count: number } {
  const dir = projectDir || process.cwd()
  const content = buildClaudeMd(dir)
  const filePath = join(dir, 'CLAUDE.md')
  writeFileSync(filePath, content, 'utf-8')
  console.log(`[DeskApp] Synced skills to ${filePath}`)
  const idx = loadIndex()
  const count = idx.skills.filter(s => s.active && s.activeFor.includes('claude-code')).length
  return { ok: true, path: filePath, count }
}

// ── Cursor: .cursorrules ──

const CURSOR_SECTION_START = '### DeskApp Skills'
const CURSOR_SECTION_END = '### End DeskApp Skills'

export function buildCursorRules(projectDir?: string): string {
  const dir = projectDir || process.cwd()
  const existingPath = join(dir, '.cursorrules')
  let existingContent = ''
  if (existsSync(existingPath)) {
    existingContent = readFileSync(existingPath, 'utf-8')
  }

  const idx = loadIndex()
  const activeSkills = idx.skills.filter(s => s.active && s.activeFor.includes('cursor'))

  // Build the DeskApp skills section
  const lines: string[] = []
  lines.push('')
  lines.push(CURSOR_SECTION_START)
  lines.push('')
  for (const entry of activeSkills) {
    const skill = getSkill(entry.name)
    if (!skill) continue
    const adapter = skill.adapters?.cursor
    const mergeSection = adapter?.mergeSection
    lines.push(`# Skill: ${skill.name}`)
    if (skill.description) lines.push(`# ${skill.description}`)
    if (skill.trigger) lines.push(`# Trigger: ${skill.trigger}`)
    if (mergeSection) lines.push(`# Section: ${mergeSection}`)
    lines.push('')
    if (skill.instructions) lines.push(skill.instructions)
    lines.push('')
  }
  lines.push(CURSOR_SECTION_END)
  lines.push('')

  const section = lines.join('\n')

  // Insert or replace the DeskApp section in existing content
  const startIdx = existingContent.indexOf(CURSOR_SECTION_START)
  const endIdx = existingContent.indexOf(CURSOR_SECTION_END)

  if (startIdx >= 0 && endIdx >= 0) {
    // Replace existing section
    return existingContent.slice(0, startIdx) + section + existingContent.slice(endIdx + CURSOR_SECTION_END.length)
  } else {
    // Append new section
    return existingContent + section
  }
}

export function syncToCursor(projectDir?: string): { ok: boolean; path: string; count: number } {
  const dir = projectDir || process.cwd()
  const content = buildCursorRules(dir)
  const filePath = join(dir, '.cursorrules')
  writeFileSync(filePath, content, 'utf-8')
  console.log(`[DeskApp] Synced skills to ${filePath}`)
  const idx = loadIndex()
  const count = idx.skills.filter(s => s.active && s.activeFor.includes('cursor')).length
  return { ok: true, path: filePath, count }
}

// ── Codex CLI: project instructions ──

export function buildCodexInstructions(projectDir?: string): string {
  const dir = projectDir || process.cwd()
  const idx = loadIndex()
  const activeSkills = idx.skills.filter(s => s.active && s.activeFor.includes('codex'))

  const sections: string[] = []
  sections.push('# DeskApp Skills for Codex')
  sections.push('')
  for (const entry of activeSkills) {
    const skill = getSkill(entry.name)
    if (!skill) continue
    const adapter = skill.adapters?.codex
    sections.push(`## ${adapter?.sectionTitle || skill.name}`)
    if (skill.description) sections.push(`> ${skill.description}`)
    if (skill.trigger) sections.push(`Trigger: ${skill.trigger}`)
    sections.push('')
    if (skill.instructions) sections.push(skill.instructions)
    if (adapter?.extraInstructions) sections.push(adapter.extraInstructions)
    sections.push('')
  }
  return sections.join('\n')
}

export function syncToCodex(projectDir?: string): { ok: boolean; path: string; count: number } {
  const dir = projectDir || process.cwd()
  const content = buildCodexInstructions(dir)
  const filePath = join(dir, 'CODEX.md')
  writeFileSync(filePath, content, 'utf-8')
  const idx = loadIndex()
  const count = idx.skills.filter(s => s.active && s.activeFor.includes('codex')).length
  return { ok: true, path: filePath, count }
}

// ── OpenClaw ──

export function buildOpenClawConfig(projectDir?: string): string {
  const dir = projectDir || process.cwd()
  const idx = loadIndex()
  const activeSkills = idx.skills.filter(s => s.active && s.activeFor.includes('openclaw'))

  const sections: string[] = []
  sections.push('# DeskApp Skills for OpenClaw')
  sections.push('')
  for (const entry of activeSkills) {
    const skill = getSkill(entry.name)
    if (!skill) continue
    sections.push(`## ${skill.name}`)
    if (skill.description) sections.push(`> ${skill.description}`)
    if (skill.trigger) sections.push(`Trigger: ${skill.trigger}`)
    sections.push('')
    if (skill.instructions) sections.push(skill.instructions)
    sections.push('')
  }
  return sections.join('\n')
}

export function syncToOpenClaw(projectDir?: string): { ok: boolean; path: string; count: number } {
  const dir = projectDir || process.cwd()
  const content = buildOpenClawConfig(dir)
  const filePath = join(dir, 'OPENCLAW.md')
  writeFileSync(filePath, content, 'utf-8')
  const idx = loadIndex()
  const count = idx.skills.filter(s => s.active && s.activeFor.includes('openclaw')).length
  return { ok: true, path: filePath, count }
}

// ── Batch sync ──

export function syncAllAgents(projectDir?: string): Record<string, any> {
  const dir = projectDir || process.cwd()
  return {
    hermes: syncToHermesViaStore(),
    claude: syncToClaudeCode(dir),
    cursor: syncToCursor(dir),
    codex: syncToCodex(dir),
    openclaw: syncToOpenClaw(dir),
  }
}

function syncToHermesViaStore(): { synced: number; failed: string[] } {
  const { syncAllToHermes } = require('./store')
  return syncAllToHermes()
}
